# docker file for local development and debugging
version: '3.3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database:/var/lib/
  appsrv:
    build: 
      context: ./appsrv
      dockerfile: Dockerfile.jvm
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
